### ISSUE TITLE
RMT issue in recent ESP IDF

### ISSUE THREAD

**Issue by MartyMacGyver** [FozzTexx/ws2812-demo#7]
FYI, there's an open issue in the ESP IDF that affects my code as well as yours when built against master - basically, the RMT is no longer producing output.

I'm opening *this* issue so you are aware and can track it in case it turns out we need to make code changes in our respective projects as a result.

https://github.com/espressif/esp-idf/issues/949

**Comment by MartyMacGyver** [comment]
I think I've got a solution...

Instead of:

    PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[gpioNum], 2);
    gpio_matrix_out(gpioNum, RMT_SIG_OUT0_IDX + RMTCHANNEL, 0, 0);
    gpio_set_direction(gpioNum, GPIO_MODE_OUTPUT);

Try:

    rmt_set_pin((rmt_channel_t)RMTCHANNEL,
                RMT_MODE_TX,
                (gpio_num_t)gpioNum);

(Edit: I use `static_cast` there but your code is not C++.)

(You'll likely need `#include <driver/rmt.h>` as well.)

**Comment by psiphi75** [comment]
I can confirm @MartyMacGyver's code fixes the issue mentioned for the latest ESP IDF.  Thanks.

**Comment by trick2011** [comment]
@MartyMacGyver 's proposed solution fixes the problem.
